# Generated by Django 2.1 on 2018-09-02 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_cases', '0001_initial'),
        ('test_plans', '0001_initial'),
        ('projects', '0002_component'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTestRun',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='date created')),
                ('upd_date', models.DateTimeField(blank=True, editable=False, verbose_name='date updated')),
                ('test_run_status', models.IntegerField(choices=[(0, 'Created'), (1, 'Active'), (2, 'Blocked'), (3, 'Completed'), (4, 'Discarded')], default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.Project')),
                ('test_plan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='test_plans.TestPlan')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical test run',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('upd_date', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('test_run_status', models.IntegerField(choices=[(0, 'Created'), (1, 'Active'), (2, 'Blocked'), (3, 'Completed'), (4, 'Discarded')], default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Project')),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='test_plans.TestPlan')),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'test_run_tab',
            },
        ),
        migrations.CreateModel(
            name='TestRunCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('actual_result', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('test_run_case_status', models.IntegerField(choices=[(0, 'Succeed'), (1, 'Failed'), (2, 'Error'), (3, 'Skipped'), (4, '-')], default=4)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_cases.TestCase')),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_runs.TestRun')),
            ],
        ),
    ]
