# Generated by Django 2.1 on 2018-09-02 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_component'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTestCase',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('test_case_type', models.IntegerField(choices=[(0, 'Functional'), (1, 'Acceptance'), (2, 'Accessibility'), (3, 'Automated'), (4, 'Compatibility'), (5, 'Performance'), (6, 'Regression'), (7, 'Security'), (8, 'Sanity'), (9, 'Usability'), (10, 'Localization')])),
                ('estimate_in_minute', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='date created')),
                ('upd_date', models.DateTimeField(blank=True, editable=False, verbose_name='date updated')),
                ('test_case_tier', models.IntegerField(choices=[(0, 'tier 0'), (1, 'tier 1'), (2, 'tier 2'), (3, 'tier 3'), (4, 'tier 4')], default=1)),
                ('test_case_platform', models.IntegerField(choices=[(0, 'Generic'), (1, 'Android'), (2, 'iOS'), (3, 'Web'), (4, 'Others')])),
                ('preconditions', models.CharField(max_length=200)),
                ('test_steps', models.CharField(max_length=2000)),
                ('expected_result', models.CharField(max_length=500)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('component', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.Component')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.Project')),
            ],
            options={
                'verbose_name': 'historical test case',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('test_case_type', models.IntegerField(choices=[(0, 'Functional'), (1, 'Acceptance'), (2, 'Accessibility'), (3, 'Automated'), (4, 'Compatibility'), (5, 'Performance'), (6, 'Regression'), (7, 'Security'), (8, 'Sanity'), (9, 'Usability'), (10, 'Localization')])),
                ('estimate_in_minute', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('upd_date', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('test_case_tier', models.IntegerField(choices=[(0, 'tier 0'), (1, 'tier 1'), (2, 'tier 2'), (3, 'tier 3'), (4, 'tier 4')], default=1)),
                ('test_case_platform', models.IntegerField(choices=[(0, 'Generic'), (1, 'Android'), (2, 'iOS'), (3, 'Web'), (4, 'Others')])),
                ('preconditions', models.CharField(max_length=200)),
                ('test_steps', models.CharField(max_length=2000)),
                ('expected_result', models.CharField(max_length=500)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Component')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Project')),
            ],
            options={
                'db_table': 'test_case_tab',
            },
        ),
    ]
