# Generated by Django 2.1 on 2018-08-22 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_auto_20180822_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRunCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('test_run_case_status', models.IntegerField(choices=[(1, 'Succeed'), (2, 'Failed'), (3, 'Error'), (4, 'Skipped'), (5, '-')], default=5)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.TestCase')),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.TestRun')),
            ],
        ),
    ]
