# Generated by Django 2.1 on 2018-08-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_auto_20180829_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltestrun',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltestrun',
            name='project',
        ),
        migrations.RemoveField(
            model_name='historicaltestrun',
            name='test_plan',
        ),
        migrations.RemoveField(
            model_name='historicaltestrun',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalTestRun',
        ),
    ]
