# Generated by Django 2.1 on 2018-08-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_testruncase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('upd_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'message_tab',
            },
        ),
    ]
