# Generated by Django 2.1 on 2018-08-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='messages',
            new_name='name',
        ),
    ]
