# Generated by Django 2.1 on 2018-08-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0006_auto_20180826_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='test_run_status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Active'), (3, 'Blocked'), (4, 'Completed')], default=1),
        ),
    ]
