# Generated by Django 2.1 on 2018-08-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0007_testrun_test_run_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('release_note', models.CharField(max_length=200)),
                ('release_status', models.IntegerField(choices=[(1, 'Created'), (2, 'Active'), (3, 'Released'), (3, 'Discarded')], default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='console.Project')),
            ],
        ),
        migrations.AlterField(
            model_name='testrun',
            name='test_run_status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Active'), (3, 'Blocked'), (4, 'Completed'), (5, 'Discarded')], default=1),
        ),
    ]
