# Generated by Django 2.1 on 2018-08-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0008_auto_20180826_1600'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='release',
            table='release_tab',
        ),
    ]
