# Generated by Django 2.1 on 2018-08-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0010_release_release_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='release_platform',
            field=models.IntegerField(choices=[(0, 'Generic'), (1, 'Android'), (2, 'iOS'), (3, 'Web'), (4, 'Others')], default=0),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Active'), (2, 'Released'), (3, 'Discarded')], default=0),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='test_case_platform',
            field=models.IntegerField(choices=[(0, 'Generic'), (1, 'Android'), (2, 'iOS'), (3, 'Web'), (4, 'Others')]),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='test_case_tier',
            field=models.IntegerField(choices=[(0, 'tier 0'), (1, 'tier 1'), (2, 'tier 2'), (3, 'tier 3'), (4, 'tier 4')], default=1),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='test_case_type',
            field=models.IntegerField(choices=[(0, 'Functional'), (1, 'Acceptance'), (2, 'Accessibility'), (3, 'Automated'), (4, 'Compatibility'), (5, 'Performance'), (6, 'Regression'), (7, 'Security'), (8, 'Sanity'), (9, 'Usability'), (10, 'Localization')]),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='test_run_status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Active'), (2, 'Blocked'), (3, 'Completed'), (4, 'Discarded')], default=0),
        ),
        migrations.AlterField(
            model_name='testruncase',
            name='test_run_case_status',
            field=models.IntegerField(choices=[(0, 'Succeed'), (1, 'Failed'), (2, 'Error'), (3, 'Skipped'), (4, '-')], default=4),
        ),
    ]
