# Generated by Django 2.1 on 2018-08-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0011_auto_20180826_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='project',
            name='upd_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
    ]
