# Generated by Django 2.1 on 2018-08-28 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0013_auto_20180828_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesterRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Role')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Tester')),
            ],
            options={
                'db_table': 'tester_role_tab',
            },
        ),
    ]
