# Generated by Django 2.1 on 2018-08-28 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0015_historicalrelease_historicaltestplan_historicaltestrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestplan',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='console.Project'),
        ),
        migrations.AddField(
            model_name='testplan',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='console.Project'),
            preserve_default=False,
        ),
    ]
