# Generated by Django 2.1 on 2018-08-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0016_auto_20180828_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestplan',
            name='test_run_status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Active'), (2, 'Completed'), (3, 'Discarded')], default=0),
        ),
        migrations.AddField(
            model_name='testplan',
            name='test_run_status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'Active'), (2, 'Completed'), (3, 'Discarded')], default=0),
        ),
    ]
