# Generated by Django 2.1 on 2018-09-29 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWeeklyReport',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('current_task_list', models.CharField(max_length=500)),
                ('created_bug_list', models.CharField(max_length=500)),
                ('followed_up_bug_list', models.CharField(max_length=500)),
                ('todo_task_list', models.CharField(max_length=500)),
                ('good_thing', models.CharField(max_length=500)),
                ('bad_thing', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='date created')),
                ('upd_date', models.DateTimeField(blank=True, editable=False, verbose_name='date updated')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical weekly report',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('current_task_list', models.CharField(max_length=500)),
                ('created_bug_list', models.CharField(max_length=500)),
                ('followed_up_bug_list', models.CharField(max_length=500)),
                ('todo_task_list', models.CharField(max_length=500)),
                ('good_thing', models.CharField(max_length=500)),
                ('bad_thing', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('upd_date', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weekly_report_tab',
            },
        ),
    ]
